title: Hacking-Capture
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
#baseurl: "/Hacking-Capture.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Safwan P # add your name
author-img: #david-freeman.jpg # add your photo
about-author: #Security Analyst # add description
social-twitter: safwan_paloli # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: safwanpaloli  # add your Github handle
social-linkedin: safwanpaloli # add your Linkedin handle
social-email: safwanpaloli6@gmail.com #add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
